services:
  postgres:
    image: ghcr.io/haathie/postgres:17
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DATABASE: postgres
    ports:
      - '5432:5432'
    command: -c shared_preload_libraries='pg_search'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5