services:
  postgres:
    image: haathie/postgres:f859711de2c17d1f5757e645a9515b32598f9c10
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DATABASE: postgres
    ports:
      - '5432:5432'
    command: -c config_file=/etc/postgresql.conf
    volumes:
      - ./dev/pg.conf:/etc/postgresql.conf
      - ./dev/pg_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096m
        reservations:
          cpus: '0.1'
          memory: 256m