services:
  postgres:
    image: ghcr.io/haathie/postgres:17
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DATABASE: postgres
    ports:
      - '5432:5432'
    command: -c config_file=/etc/postgresql.conf
    volumes:
      - ./dev/pg.conf:/etc/postgresql.conf
      - ./dev/pg_data:/var/lib/postgresql/data:z
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096m
        reservations:
          cpus: '0.1'
          memory: 256m
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5